export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST"

export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"

export const GET_PRODUCT_FAILURE="GET_PRODUCT_FAILURE"

export const SET_CART = "SET_CART"

export const DELETE_CART = "DELETE_CART"